### ISSUE TITLE
TypeError: crypto.randomUUID is not a function

### ISSUE THREAD

**Issue by yyjjjj** [LayerXcom/next-navigation-guard#4]
I am trying to use your library, but I have encountered an issue during the setup of my development environment.

I am working with Node v20.11.1 and Next.js v14.1.3. I wrapped the children by `NavigationGuardProvider` in `app/layout`, but I received the following error: `'TypeError: crypto.randomUUID is not a function'`. (Please see the attached image below).

![image](https://github.com/user-attachments/assets/b467d382-adad-497a-884b-65b54361b6e3)

After some investigation, I suspect that the issue might be related to the fact that `crypto.randomUUID` is not enabled in an HTTP (localhost) environment, as mentioned [here](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID).

I would like to run this library in an HTTP environment. Could you advise if there is something I might be missing in this setup? Thank you!

**Comment by yyjjjj** [comment]
I have used your code structure as a guide for my implementation, and it was very helpful. Thank you for your work!

**Comment by IvanGrekov** [comment]
> I have used your code structure as a guide for my implementation, and it was very helpful. Thank you for your work!

Hi, sorry, how did you resolve the issue?

**Comment by yyjjjj** [comment]
@IvanGrekov Hi, Sorry for the late reply.

I replaced the newToken function in [`src/utils/historyAugmentation.tsx`](https://github.com/LayerXcom/next-navigation-guard/blob/main/src/utils/historyAugmentation.tsx#L9-L11) with using [crypto getRandomValues](https://developer.mozilla.org/ko/docs/Web/API/Crypto/getRandomValues) and kept the other logic.

I didn't need some of the logic in this repo, so I only referenced the code I needed,
but you can fork this repo and just change the newToken function above.

I hope this helps you in your work!
